services:
  db:
    image: postgres:16-alpine
    container_name: angular_admin_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: angular_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d angular_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
